---
- name: install packages for baikal
  apt: pkg=$item state=installed
  with_items:
    - php5-cli

#
# nginx
- name: copy baikal nginx config to server
  template: src=files/etc/nginx/sites-available/baikal.nginx dest=/etc/nginx/sites-available/baikal.nginx mode=0600
- file: src=/etc/nginx/sites-available/baikal.nginx dest=/etc/nginx/sites-enabled/baikal.nginx state=link
  notify:
    - restart nginx

#
# baikal
- name: create baikal homedir
  command: mkdir -p ${baikal_dir}

- name: checkout baikal
  git: repo=https://github.com/jeromeschneider/Baikal.git dest=${baikal_dir}
  register: baikal_git

- name: download up composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=${baikal_dir}

- name: install dependencies
  shell: cd ${baikal_dir}; php composer.phar install

- name: set baikal permissions
  shell: chown -R root:www-data ${baikal_dir} && chmod -R g+rw ${baikal_dir}/Specific
  only_if: ${baikal_git.changed}

- name: enable baikal
  shell: echo 1 >${baikal_dir}/Specific/ENABLE_INSTALL
  only_if: ${baikal_git.changed}
