---
- name: install packages for baikal
  apt: pkg=$item state=installed
  with_items:
    - php5-cli

##
## nginx
- name: copy baikal nginx config to server
  template: src=files/etc/nginx/sites-available/baikal.nginx dest=/etc/nginx/sites-available/baikal.nginx mode=0600
- file: src=/etc/nginx/sites-available/baikal.nginx dest=/etc/nginx/sites-enabled/baikal.nginx state=link
  notify:
    - restart nginx

#
# baikal
- name: checkout baikal
  git: repo=https://github.com/jeromeschneider/Baikal.git dest={{ baikal_dir }}
  register: baikal_git

- name: download up composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir={{ baikal_dir }}
  when: not baikal_git.before

- name: install dependencies
  shell: cd {{ baikal_dir }}; php composer.phar install

- name: set baikal permissions
  file: path={{ baikal_dir }} owner=root group=www-data recurse=yes state=directory
  when: baikal_git.changed

- name: Specific is writable
  file: path={{ baikal_dir }}/Specific mode=0770 recurse=yes state=directory
  when: baikal_git.changed

- name: enable baikal install
  copy: content="" dest={{ baikal_dir }}/Specific/ENABLE_INSTALL
  when: not baikal_git.before
