---
- name: install packages for baikal
  apt: pkg=$item state=installed
  with_items:
    - nginx
    - php5-cgi
    - php5-sqlite
    - php-apc
    - git

#
# php fcgi script
- name: copy php-cgi init script to server
  copy: src=files/etc/init.d/php-cgi dest=/etc/init.d/php-cgi

- name: set php-cgi permissions
  file: path=/etc/init.d/php-cgi mode=0755
  notify:
    - start php-cgi

- name: patch php.ini
  file: src=files/etc/php5/cgi/php.ini dest=/etc/php5/cgi/php.ini
  notify:
    - start php-cgi

#
# nginx
- name: copy baikal nginx config to server
  template: src=files/etc/nginx/sites-available/baikal.nginx dest=/etc/nginx/sites-available/baikal.nginx mode=0600
- file: src=/etc/nginx/sites-available/baikal.nginx dest=/etc/nginx/sites-enabled/baikal.nginx state=link
  notify:
    - restart nginx

#
# baikal
- name: create baikal homedir
  command: mkdir -p ${baikal_dir}

- name: checkout baikal
  git: repo=https://github.com/jeromeschneider/Baikal.git dest=${baikal_dir}
  register: baikal_git

- name: set baikal permissions
  shell: chown -R root:www-data ${baikal_dir} && chmod -R g+rw ${baikal_dir}/Specific
  only_if: ${baikal_git.changed}

- name: enable baikal
  shell: echo 1 >${baikal_dir}/Specific/ENABLE_INSTALL
  only_if: ${baikal_git.changed}
